#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x $(which tsc) ]; then
	typescript="tsc"
else
	typescript="$basedir/../node_modules/typescript/bin/tsc"
fi

exec $typescript "--sourcemap" "--module" "commonjs" "bin/www.ts"
