#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x $(which bower) ]; then
	bower install
else
	node "$basedir/../node_modules/bower/bin/bower" "install"

fi

# If bower has failed - exit
if [ $? -ne 0 ] ; then
	exit $?
fi

if [ -x $(which tsd) ] ; then
	tsd reinstall -so
else
	node "$basedir/../node_modules/tsd/build/cli.js" "reinstall" "-so"
fi

exit $?
