#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../node_modules/bower/bin/bower" "install"
  "$basedir/node"  "$basedir/../node_modules/tsd/build/cli.js" "reinstall" "-so"
  ret=$?
else
  node  "$basedir/../node_modules/bower/bin/bower" "install"
  node  "$basedir/../node_modules/tsd/build/cli.js" "reinstall" "-so"
  ret=$?
fi
exit $ret
