#!/bin/sh

if [ -x $(which mongoimport) ]; then
	mongoimport --host localhost --port 27017 --collection homes --db bibliothek --jsonArray --file ./homes_data.json --verbose
else
	echo "Cannot find an executable \`mongoimport\`"
	exit
fi

